#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# check build has completed
git status --porcelain \
    | grep -e '^[AM].*' \
    | awk '{ print $2 }' \
    | grep -i -e '[^/]*\.sh' \
    | wc -l \
    | while read updated_sh
do
    if [[ $updated_sh -ne 0 ]]; then
        git status --porcelain \
            | grep -e '^[AM].*' \
            | awk '{ print $2 }' \
            | grep -i -e 'bin/.*' \
            | wc -l \
            | while read updated_script
        do
            if [[ $updated_script -eq 0 ]]; then
                echo "git pre-commit error: build has not completed." >&2
                echo "make update:"
                sleep 3s
                make update
                exit 1
            fi
        done
    fi
done
if [ $? -ne 0 ]; then
    exit 1
fi

# make-test check
git status --porcelain \
    | grep -e '^[AM].*' \
    | awk '{ print $2 }' \
    | grep -iq -e 'Makefile' -e '.*\.sh' -e '.*\.bats'
if [ $? -eq 0 ]; then
    echo make test:
    make test
    if [ $? -ne 0 ]; then
        echo "git pre-commit error: test has failed." >&2
        exit 1
    fi
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
